-- ============================================================================
-- Table: users
-- Description:
--   Stores core user identity records, including secure password hashes.
--   Uses Rust-generated UUIDv7 for clustered B-Tree indexing performance.
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    -- Primary key: UUIDv7 generated by the application layer.
    id UUID PRIMARY KEY,

    -- Enforced uniqueness to prevent identity collision.
    username TEXT NOT NULL UNIQUE,

    -- Stored output of the Argon2id key derivation function.
    password_hash TEXT NOT NULL,

    -- Audit timestamp using UTC.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Optimize queries for authentication lookups.
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
