# GNU AFFERO GENERAL PUBLIC LICENSE
# Version 3, 19 November 2007
#
# Copyright (C) 2026 Mathew Aloisio
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# justfile (Contracts Pipeline)

# Configure the execution shell for Windows environments.
set windows-shell := ["cmd.exe", "/c"]

# Compile Protocol Buffers to C# source files and build the .NET Standard 2.0 assembly.
build:
    @echo Compiling Protocol Buffers to C# source...
    python build_contracts.py
    @echo Restoring .NET dependencies for Standard 2.0...
    dotnet restore ../dot-net-apis/OcLink.API.Core -p:TargetFramework=netstandard2.0
    @echo Compiling .NET Standard 2.0 API assembly...
    dotnet build ../dot-net-apis/OcLink.API.Core -c Release -f netstandard2.0 --no-restore
    @echo Compilation complete. Target assembly ready for distribution.
